import { getAccessToken } from './auth';

export type UserRole = 'admin' | 'manager' | 'staff' | 'unknown';

export const TENANT_PERMISSIONS = Object.freeze({
  DASHBOARD_READ: 'dashboard.read',

  PRODUCTS_READ: 'products.read',
  PRODUCTS_WRITE: 'products.write',

  PRODUCT_PACKAGES_READ: 'product_packages.read',
  PRODUCT_PACKAGES_WRITE: 'product_packages.write',

  SUPPLIERS_READ: 'suppliers.read',
  SUPPLIERS_WRITE: 'suppliers.write',

  STORAGE_LOCATIONS_READ: 'storage_locations.read',
  STORAGE_LOCATIONS_WRITE: 'storage_locations.write',

  STOCK_READ: 'stock.read',
  STOCK_CONSUME: 'stock.consume',
  STOCK_COUNT: 'stock.count',
  STOCK_ADJUST: 'stock.adjust',
  STOCK_MOVEMENTS_READ: 'stock_movements.read',
  STOCK_TRANSFERS_READ: 'stock_transfers.read',
  STOCK_TRANSFERS_CREATE: 'stock_transfers.create',
  STOCK_TRANSFERS_UPDATE: 'stock_transfers.update',
  STOCK_TRANSFERS_EXECUTE: 'stock_transfers.execute',
  STOCK_TRANSFERS_CANCEL: 'stock_transfers.cancel',

  PURCHASE_ORDERS_READ: 'purchase_orders.read',
  PURCHASE_ORDERS_CREATE: 'purchase_orders.create',
  PURCHASE_ORDERS_UPDATE: 'purchase_orders.update',
  PURCHASE_ORDERS_SUBMIT: 'purchase_orders.submit',
  PURCHASE_ORDERS_APPROVE: 'purchase_orders.approve',
  PURCHASE_ORDERS_CANCEL: 'purchase_orders.cancel',

  SHIPMENTS_READ: 'shipments.read',
  SHIPMENTS_WRITE: 'shipments.write',
  SHIPMENTS_SEND: 'shipments.send',
  SHIPMENTS_RECEIVE: 'shipments.receive',
  SHIPMENTS_FINALIZE: 'shipments.finalize',
  SHIPMENTS_AUTO_REORDER: 'shipments.auto_reorder',

  SHIPMENT_ITEMS_READ: 'shipment_items.read',
  SHIPMENT_ITEMS_WRITE: 'shipment_items.write',

  ALERTS_READ: 'alerts.read',
  ALERTS_WRITE: 'alerts.write',
  ALERTS_OVERRIDE: 'alerts.override',

  REPORTS_READ: 'reports.read',
  INSIGHTS_READ: 'insights.read',

  TENANT_READ: 'tenant.read',
  TENANT_UPDATE: 'tenant.update',
  TENANT_DELETE: 'tenant.delete',

  USERS_READ: 'users.read',
  USERS_WRITE: 'users.write',

  SYSTEM_STATUS_READ: 'system_status.read',
  SYSTEM_CONTEXT_READ: 'system_context.read',

  EXECUTION_REQUESTS_VIEW: 'execution_requests.view',
  EXECUTION_REQUESTS_CREATE: 'execution_requests.create',
  EXECUTION_REQUESTS_SUBMIT: 'execution_requests.submit',
  EXECUTION_REQUESTS_CANCEL: 'execution_requests.cancel',
  EXECUTION_REQUESTS_REVIEW: 'execution_requests.review',
  EXECUTION_REQUESTS_EXECUTE: 'execution_requests.execute',

  AUTOMATION_SCHEDULES_VIEW: 'automation_schedules.view',
  AUTOMATION_SCHEDULES_CREATE: 'automation_schedules.create',
  AUTOMATION_SCHEDULES_UPDATE: 'automation_schedules.update',
  AUTOMATION_SCHEDULES_PAUSE: 'automation_schedules.pause',
  AUTOMATION_SCHEDULES_RESUME: 'automation_schedules.resume',
  AUTOMATION_SCHEDULES_DISABLE: 'automation_schedules.disable',

  TENANT_DIAGNOSTICS_READ: 'tenant_diagnostics.read',
  AUDIT_READ: 'audit.read'
} as const);

export type TenantPermission = (typeof TENANT_PERMISSIONS)[keyof typeof TENANT_PERMISSIONS];

type JwtPayload = {
  role?: string;
  tenant_id?: string;
  id?: string;
  exp?: number;
};

function decodeJwtPayload(token: string | null): JwtPayload | null {
  if (!token) {
    return null;
  }

  try {
    const parts = token.split('.');

    if (parts.length !== 3) {
      return null;
    }

    const base64 = parts[1].replace(/-/g, '+').replace(/_/g, '/');
    const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, '=');
    const decoded = atob(padded);

    return JSON.parse(decoded) as JwtPayload;
  } catch {
    return null;
  }
}

export const ROLE_PERMISSIONS: Record<Exclude<UserRole, 'unknown'>, readonly TenantPermission[]> = Object.freeze({
  admin: Object.freeze([
    TENANT_PERMISSIONS.DASHBOARD_READ,
    TENANT_PERMISSIONS.PRODUCTS_READ,
    TENANT_PERMISSIONS.PRODUCTS_WRITE,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_READ,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_WRITE,
    TENANT_PERMISSIONS.SUPPLIERS_READ,
    TENANT_PERMISSIONS.SUPPLIERS_WRITE,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_READ,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_WRITE,
    TENANT_PERMISSIONS.STOCK_READ,
    TENANT_PERMISSIONS.STOCK_COUNT,
    TENANT_PERMISSIONS.STOCK_ADJUST,
    TENANT_PERMISSIONS.STOCK_MOVEMENTS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CREATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_UPDATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_EXECUTE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CANCEL,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_READ,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CREATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_UPDATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_SUBMIT,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_APPROVE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CANCEL,
    TENANT_PERMISSIONS.SHIPMENTS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_WRITE,
    TENANT_PERMISSIONS.SHIPMENTS_SEND,
    TENANT_PERMISSIONS.SHIPMENTS_RECEIVE,
    TENANT_PERMISSIONS.SHIPMENTS_FINALIZE,
    TENANT_PERMISSIONS.SHIPMENTS_AUTO_REORDER,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_READ,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_WRITE,
    TENANT_PERMISSIONS.ALERTS_READ,
    TENANT_PERMISSIONS.ALERTS_WRITE,
    TENANT_PERMISSIONS.ALERTS_OVERRIDE,
    TENANT_PERMISSIONS.REPORTS_READ,
    TENANT_PERMISSIONS.INSIGHTS_READ,
    TENANT_PERMISSIONS.TENANT_READ,
    TENANT_PERMISSIONS.TENANT_UPDATE,
    TENANT_PERMISSIONS.TENANT_DELETE,
    TENANT_PERMISSIONS.USERS_READ,
    TENANT_PERMISSIONS.USERS_WRITE,
    TENANT_PERMISSIONS.SYSTEM_STATUS_READ,
    TENANT_PERMISSIONS.SYSTEM_CONTEXT_READ,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_VIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_SUBMIT,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CANCEL,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_REVIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_EXECUTE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_VIEW,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_CREATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_UPDATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_PAUSE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_RESUME,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_DISABLE,
    TENANT_PERMISSIONS.TENANT_DIAGNOSTICS_READ,
    TENANT_PERMISSIONS.AUDIT_READ
  ]),

  manager: Object.freeze([
    TENANT_PERMISSIONS.DASHBOARD_READ,
    TENANT_PERMISSIONS.PRODUCTS_READ,
    TENANT_PERMISSIONS.PRODUCTS_WRITE,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_READ,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_WRITE,
    TENANT_PERMISSIONS.SUPPLIERS_READ,
    TENANT_PERMISSIONS.SUPPLIERS_WRITE,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_READ,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_WRITE,
    TENANT_PERMISSIONS.STOCK_READ,
    TENANT_PERMISSIONS.STOCK_CONSUME,
    TENANT_PERMISSIONS.STOCK_COUNT,
    TENANT_PERMISSIONS.STOCK_ADJUST,
    TENANT_PERMISSIONS.STOCK_MOVEMENTS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CREATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_UPDATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_EXECUTE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CANCEL,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_READ,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CREATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_UPDATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_SUBMIT,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_APPROVE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CANCEL,
    TENANT_PERMISSIONS.SHIPMENTS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_WRITE,
    TENANT_PERMISSIONS.SHIPMENTS_SEND,
    TENANT_PERMISSIONS.SHIPMENTS_RECEIVE,
    TENANT_PERMISSIONS.SHIPMENTS_FINALIZE,
    TENANT_PERMISSIONS.SHIPMENTS_AUTO_REORDER,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_READ,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_WRITE,
    TENANT_PERMISSIONS.ALERTS_READ,
    TENANT_PERMISSIONS.ALERTS_WRITE,
    TENANT_PERMISSIONS.REPORTS_READ,
    TENANT_PERMISSIONS.INSIGHTS_READ,
    TENANT_PERMISSIONS.TENANT_READ,
    TENANT_PERMISSIONS.USERS_READ,
    TENANT_PERMISSIONS.SYSTEM_STATUS_READ,
    TENANT_PERMISSIONS.SYSTEM_CONTEXT_READ,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_VIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_SUBMIT,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CANCEL,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_REVIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_EXECUTE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_VIEW,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_CREATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_UPDATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_PAUSE,
    TENANT_PERMISSIONS.AUDIT_READ
  ]),

  staff: Object.freeze([
    TENANT_PERMISSIONS.DASHBOARD_READ,
    TENANT_PERMISSIONS.PRODUCTS_READ,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_READ,
    TENANT_PERMISSIONS.SUPPLIERS_READ,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_READ,
    TENANT_PERMISSIONS.STOCK_READ,
    TENANT_PERMISSIONS.STOCK_CONSUME,
    TENANT_PERMISSIONS.STOCK_COUNT,
    TENANT_PERMISSIONS.STOCK_MOVEMENTS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_READ,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_RECEIVE,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_READ,
    TENANT_PERMISSIONS.ALERTS_READ,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_VIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CREATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_VIEW,
    TENANT_PERMISSIONS.TENANT_READ
  ])
});

export function getCurrentUserRole(): UserRole {
  const payload = decodeJwtPayload(getAccessToken());
  const role = payload?.role;

  if (role === 'admin' || role === 'manager' || role === 'staff') {
    return role;
  }

  return 'unknown';
}

export function permissionsForRole(role: UserRole = getCurrentUserRole()): readonly TenantPermission[] {
  if (role === 'admin' || role === 'manager' || role === 'staff') {
    return ROLE_PERMISSIONS[role];
  }

  return [];
}

export function hasPermission(permission: TenantPermission, role: UserRole = getCurrentUserRole()): boolean {
  return permissionsForRole(role).includes(permission);
}

export function hasAllPermissions(permissions: TenantPermission[], role: UserRole = getCurrentUserRole()): boolean {
  return permissions.every((permission) => hasPermission(permission, role));
}

export function hasAnyPermission(permissions: TenantPermission[], role: UserRole = getCurrentUserRole()): boolean {
  return permissions.some((permission) => hasPermission(permission, role));
}

export function hasAnyRole(allowedRoles: UserRole[]): boolean {
  const currentRole = getCurrentUserRole();
  return allowedRoles.includes(currentRole);
}

export function getRoleCapabilities(role: UserRole = getCurrentUserRole()) {
  const can = (permission: TenantPermission) => hasPermission(permission, role);

  return {
    role,
    isAdmin: role === 'admin',
    isManager: role === 'manager',
    isStaff: role === 'staff',
    canViewReports: can(TENANT_PERMISSIONS.REPORTS_READ),
    canViewInsights: can(TENANT_PERMISSIONS.INSIGHTS_READ),
    canViewUsers: can(TENANT_PERMISSIONS.USERS_READ),
    canManageUsers: can(TENANT_PERMISSIONS.USERS_WRITE),
    canViewAdminSystem: can(TENANT_PERMISSIONS.SYSTEM_STATUS_READ),
    canManageProducts: can(TENANT_PERMISSIONS.PRODUCTS_WRITE),
    canManageSuppliers: can(TENANT_PERMISSIONS.SUPPLIERS_WRITE),
    canManageStorageLocations: can(TENANT_PERMISSIONS.STORAGE_LOCATIONS_WRITE),
    canManageAlerts: can(TENANT_PERMISSIONS.ALERTS_WRITE),
    canManageShipments: can(TENANT_PERMISSIONS.SHIPMENTS_WRITE),
    canReceiveShipments: can(TENANT_PERMISSIONS.SHIPMENTS_RECEIVE),
    canConsumeStock: can(TENANT_PERMISSIONS.STOCK_CONSUME),
    canCountStock: can(TENANT_PERMISSIONS.STOCK_COUNT),
    canAdjustStock: can(TENANT_PERMISSIONS.STOCK_ADJUST),
    canViewStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_READ),
    canCreateStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_CREATE),
    canUpdateStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_UPDATE),
    canExecuteStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_EXECUTE),
    canCancelStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_CANCEL),
    canViewPurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_READ),
    canCreatePurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_CREATE),
    canUpdatePurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_UPDATE),
    canSubmitPurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_SUBMIT),
    canApprovePurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_APPROVE),
    canCancelPurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_CANCEL),
    canViewSessions: role === 'admin' || role === 'manager' || role === 'staff',
    canViewAudit: can(TENANT_PERMISSIONS.AUDIT_READ)
  };
}
