import { getAccessToken } from './auth';

export type UserRole = 'admin' | 'manager' | 'staff' | 'unknown';

export const TENANT_PERMISSIONS = Object.freeze({
  DASHBOARD_READ: 'dashboard.read',

  PRODUCTS_READ: 'products.read',
  PRODUCTS_WRITE: 'products.write',

  PRODUCT_PACKAGES_READ: 'product_packages.read',
  PRODUCT_PACKAGES_WRITE: 'product_packages.write',

  SUPPLIERS_READ: 'suppliers.read',
  SUPPLIERS_WRITE: 'suppliers.write',

  STORAGE_LOCATIONS_READ: 'storage_locations.read',
  STORAGE_LOCATIONS_WRITE: 'storage_locations.write',

  STOCK_READ: 'stock.read',
  STOCK_CONSUME: 'stock.consume',
  STOCK_COUNT: 'stock.count',
  STOCK_ADJUST: 'stock.adjust',
  STOCK_MOVEMENTS_READ: 'stock_movements.read',
  STOCK_TRANSFERS_READ: 'stock_transfers.read',
  STOCK_TRANSFERS_CREATE: 'stock_transfers.create',
  STOCK_TRANSFERS_UPDATE: 'stock_transfers.update',
  STOCK_TRANSFERS_EXECUTE: 'stock_transfers.execute',
  STOCK_TRANSFERS_CANCEL: 'stock_transfers.cancel',

  INVENTORY_USAGE_READ: 'inventory_usage.read',
  INVENTORY_USAGE_RECORD: 'inventory_usage.record',
  INVENTORY_USAGE_BULK_RECORD: 'inventory_usage.bulk_record',
  INVENTORY_USAGE_REVERSE: 'inventory_usage.reverse',
  INVENTORY_USAGE_REVIEW: 'inventory_usage.review',
  INVENTORY_USAGE_CLOSE_PERIOD: 'inventory_usage.close_period',
  INVENTORY_USAGE_MANAGE_TEMPLATES: 'inventory_usage.manage_templates',
  INVENTORY_USAGE_RUN_SCHEDULED: 'inventory_usage.run_scheduled',

  INVENTORY_REQUISITIONS_READ: 'inventory_requisitions.read',
  INVENTORY_REQUISITIONS_CREATE: 'inventory_requisitions.create',
  INVENTORY_REQUISITIONS_SUBMIT: 'inventory_requisitions.submit',
  INVENTORY_REQUISITIONS_APPROVE: 'inventory_requisitions.approve',
  INVENTORY_REQUISITIONS_FULFILL: 'inventory_requisitions.fulfill',
  INVENTORY_REQUISITIONS_CANCEL: 'inventory_requisitions.cancel',

  INVENTORY_RESERVATIONS_READ: 'inventory_reservations.read',
  INVENTORY_RESERVATIONS_CREATE: 'inventory_reservations.create',
  INVENTORY_RESERVATIONS_ALLOCATE: 'inventory_reservations.allocate',
  INVENTORY_RESERVATIONS_FULFILL: 'inventory_reservations.fulfill',
  INVENTORY_RESERVATIONS_RELEASE: 'inventory_reservations.release',
  INVENTORY_RESERVATIONS_CANCEL: 'inventory_reservations.cancel',
  INVENTORY_RESERVATIONS_EXPIRE: 'inventory_reservations.expire',

  PURCHASE_ORDERS_READ: 'purchase_orders.read',
  PURCHASE_ORDERS_CREATE: 'purchase_orders.create',
  PURCHASE_ORDERS_UPDATE: 'purchase_orders.update',
  PURCHASE_ORDERS_SUBMIT: 'purchase_orders.submit',
  PURCHASE_ORDERS_APPROVE: 'purchase_orders.approve',
  PURCHASE_ORDERS_CANCEL: 'purchase_orders.cancel',

  SHIPMENTS_READ: 'shipments.read',
  SHIPMENTS_WRITE: 'shipments.write',
  SHIPMENTS_SEND: 'shipments.send',
  SHIPMENTS_RECEIVE: 'shipments.receive',
  SHIPMENTS_FINALIZE: 'shipments.finalize',
  SHIPMENTS_AUTO_REORDER: 'shipments.auto_reorder',

  SHIPMENT_ITEMS_READ: 'shipment_items.read',
  SHIPMENT_ITEMS_WRITE: 'shipment_items.write',

  ALERTS_READ: 'alerts.read',
  ALERTS_WRITE: 'alerts.write',
  ALERTS_OVERRIDE: 'alerts.override',

  REPORTS_READ: 'reports.read',
  INSIGHTS_READ: 'insights.read',
  OPERATIONAL_ACTION_CENTER_READ: 'operational_action_center.read',
  PLATFORM_RELIABILITY_READ: 'platform_reliability.read',

  TENANT_READ: 'tenant.read',
  TENANT_UPDATE: 'tenant.update',
  TENANT_DELETE: 'tenant.delete',

  USERS_READ: 'users.read',
  USERS_WRITE: 'users.write',

  SYSTEM_STATUS_READ: 'system_status.read',
  SYSTEM_CONTEXT_READ: 'system_context.read',

  EXECUTION_REQUESTS_VIEW: 'execution_requests.view',
  EXECUTION_REQUESTS_CREATE: 'execution_requests.create',
  EXECUTION_REQUESTS_SUBMIT: 'execution_requests.submit',
  EXECUTION_REQUESTS_CANCEL: 'execution_requests.cancel',
  EXECUTION_REQUESTS_REVIEW: 'execution_requests.review',
  EXECUTION_REQUESTS_EXECUTE: 'execution_requests.execute',

  EXECUTION_TASKS_READ: 'execution_tasks.read',
  EXECUTION_TASKS_CREATE: 'execution_tasks.create',
  EXECUTION_TASKS_ASSIGN: 'execution_tasks.assign',
  EXECUTION_TASKS_UPDATE: 'execution_tasks.update',
  EXECUTION_TASKS_CANCEL: 'execution_tasks.cancel',
  EXECUTION_TASKS_COMPLETE: 'execution_tasks.complete',

  INVENTORY_OPTIMIZATION_READ: 'inventory_optimization.read',
  INVENTORY_OPTIMIZATION_CREATE: 'inventory_optimization.create',
  INVENTORY_OPTIMIZATION_GOVERN: 'inventory_optimization.govern',

  AUTOMATION_SCHEDULES_VIEW: 'automation_schedules.view',
  AUTOMATION_SCHEDULES_CREATE: 'automation_schedules.create',
  AUTOMATION_SCHEDULES_UPDATE: 'automation_schedules.update',
  AUTOMATION_SCHEDULES_PAUSE: 'automation_schedules.pause',
  AUTOMATION_SCHEDULES_RESUME: 'automation_schedules.resume',
  AUTOMATION_SCHEDULES_DISABLE: 'automation_schedules.disable',

  TENANT_DIAGNOSTICS_READ: 'tenant_diagnostics.read',
  AUDIT_READ: 'audit.read',

  PAR_LEVELS_READ: 'par_levels.read',
  PAR_LEVELS_WRITE: 'par_levels.write',
  CYCLE_COUNTS_READ: 'cycle_counts.read',
  CYCLE_COUNTS_WRITE: 'cycle_counts.write',
  CYCLE_COUNTS_APPROVE: 'cycle_counts.approve',
  REQUISITIONS_READ: 'requisitions.read',
  REQUISITIONS_CREATE: 'requisitions.create',
  APPROVAL_RULES_READ: 'approval_rules.read',
  APPROVAL_RULES_WRITE: 'approval_rules.write',
  APPROVALS_EXECUTE: 'approvals.execute',
  SUPPLIER_CATALOG_READ: 'supplier_catalog.read',
  SUPPLIER_CATALOG_WRITE: 'supplier_catalog.write',
  INVOICES_READ: 'invoices.read',
  INVOICES_WRITE: 'invoices.write',
  ATTACHMENTS_READ: 'attachments.read',
  ATTACHMENTS_WRITE: 'attachments.write',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_WRITE: 'notifications.write',
  BARCODE_LABELS_READ: 'barcode_labels.read',
  BARCODE_LABELS_WRITE: 'barcode_labels.write',
} as const);

export type TenantPermission = (typeof TENANT_PERMISSIONS)[keyof typeof TENANT_PERMISSIONS];

type JwtPayload = {
  role?: string;
  tenant_id?: string;
  id?: string;
  exp?: number;
};

function decodeJwtPayload(token: string | null): JwtPayload | null {
  if (!token) {
    return null;
  }

  try {
    const parts = token.split('.');

    if (parts.length !== 3) {
      return null;
    }

    const base64 = parts[1].replace(/-/g, '+').replace(/_/g, '/');
    const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, '=');
    const decoded = atob(padded);

    return JSON.parse(decoded) as JwtPayload;
  } catch {
    return null;
  }
}

export const ROLE_PERMISSIONS: Record<Exclude<UserRole, 'unknown'>, readonly TenantPermission[]> = Object.freeze({
  admin: Object.freeze([
    TENANT_PERMISSIONS.DASHBOARD_READ,
    TENANT_PERMISSIONS.PRODUCTS_READ,
    TENANT_PERMISSIONS.PRODUCTS_WRITE,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_READ,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_WRITE,
    TENANT_PERMISSIONS.SUPPLIERS_READ,
    TENANT_PERMISSIONS.SUPPLIERS_WRITE,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_READ,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_WRITE,
    TENANT_PERMISSIONS.STOCK_READ,
    TENANT_PERMISSIONS.STOCK_COUNT,
    TENANT_PERMISSIONS.STOCK_ADJUST,
    TENANT_PERMISSIONS.STOCK_MOVEMENTS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CREATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_UPDATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_EXECUTE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CANCEL,
    TENANT_PERMISSIONS.INVENTORY_USAGE_READ,
    TENANT_PERMISSIONS.INVENTORY_USAGE_RECORD,
    TENANT_PERMISSIONS.INVENTORY_USAGE_BULK_RECORD,
    TENANT_PERMISSIONS.INVENTORY_USAGE_REVERSE,
    TENANT_PERMISSIONS.INVENTORY_USAGE_REVIEW,
    TENANT_PERMISSIONS.INVENTORY_USAGE_CLOSE_PERIOD,
    TENANT_PERMISSIONS.INVENTORY_USAGE_MANAGE_TEMPLATES,
    TENANT_PERMISSIONS.INVENTORY_USAGE_RUN_SCHEDULED,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_READ,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_CREATE,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_SUBMIT,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_APPROVE,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_FULFILL,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_CANCEL,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_READ,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_CREATE,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_ALLOCATE,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_FULFILL,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_RELEASE,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_CANCEL,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_EXPIRE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_READ,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CREATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_UPDATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_SUBMIT,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_APPROVE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CANCEL,
    TENANT_PERMISSIONS.SHIPMENTS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_WRITE,
    TENANT_PERMISSIONS.SHIPMENTS_SEND,
    TENANT_PERMISSIONS.SHIPMENTS_RECEIVE,
    TENANT_PERMISSIONS.SHIPMENTS_FINALIZE,
    TENANT_PERMISSIONS.SHIPMENTS_AUTO_REORDER,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_READ,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_WRITE,
    TENANT_PERMISSIONS.ALERTS_READ,
    TENANT_PERMISSIONS.ALERTS_WRITE,
    TENANT_PERMISSIONS.ALERTS_OVERRIDE,
    TENANT_PERMISSIONS.REPORTS_READ,
    TENANT_PERMISSIONS.INSIGHTS_READ,
    TENANT_PERMISSIONS.OPERATIONAL_ACTION_CENTER_READ,
    TENANT_PERMISSIONS.PLATFORM_RELIABILITY_READ,
    TENANT_PERMISSIONS.TENANT_READ,
    TENANT_PERMISSIONS.TENANT_UPDATE,
    TENANT_PERMISSIONS.TENANT_DELETE,
    TENANT_PERMISSIONS.USERS_READ,
    TENANT_PERMISSIONS.USERS_WRITE,
    TENANT_PERMISSIONS.SYSTEM_STATUS_READ,
    TENANT_PERMISSIONS.SYSTEM_CONTEXT_READ,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_VIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_SUBMIT,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CANCEL,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_REVIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_EXECUTE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_READ,
    TENANT_PERMISSIONS.EXECUTION_TASKS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_ASSIGN,
    TENANT_PERMISSIONS.EXECUTION_TASKS_UPDATE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_CANCEL,
    TENANT_PERMISSIONS.EXECUTION_TASKS_COMPLETE,
    TENANT_PERMISSIONS.INVENTORY_OPTIMIZATION_READ,
    TENANT_PERMISSIONS.INVENTORY_OPTIMIZATION_CREATE,
    TENANT_PERMISSIONS.INVENTORY_OPTIMIZATION_GOVERN,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_VIEW,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_CREATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_UPDATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_PAUSE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_RESUME,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_DISABLE,
    TENANT_PERMISSIONS.TENANT_DIAGNOSTICS_READ,
    TENANT_PERMISSIONS.AUDIT_READ,
    TENANT_PERMISSIONS.PAR_LEVELS_READ,
    TENANT_PERMISSIONS.PAR_LEVELS_WRITE,
    TENANT_PERMISSIONS.CYCLE_COUNTS_READ,
    TENANT_PERMISSIONS.CYCLE_COUNTS_WRITE,
    TENANT_PERMISSIONS.CYCLE_COUNTS_APPROVE,
    TENANT_PERMISSIONS.REQUISITIONS_READ,
    TENANT_PERMISSIONS.REQUISITIONS_CREATE,
    TENANT_PERMISSIONS.APPROVAL_RULES_READ,
    TENANT_PERMISSIONS.APPROVAL_RULES_WRITE,
    TENANT_PERMISSIONS.APPROVALS_EXECUTE,
    TENANT_PERMISSIONS.SUPPLIER_CATALOG_READ,
    TENANT_PERMISSIONS.SUPPLIER_CATALOG_WRITE,
    TENANT_PERMISSIONS.INVOICES_READ,
    TENANT_PERMISSIONS.INVOICES_WRITE,
    TENANT_PERMISSIONS.ATTACHMENTS_READ,
    TENANT_PERMISSIONS.ATTACHMENTS_WRITE,
    TENANT_PERMISSIONS.NOTIFICATIONS_READ,
    TENANT_PERMISSIONS.NOTIFICATIONS_WRITE,
    TENANT_PERMISSIONS.BARCODE_LABELS_READ,
    TENANT_PERMISSIONS.BARCODE_LABELS_WRITE
  ]),

  manager: Object.freeze([
    TENANT_PERMISSIONS.DASHBOARD_READ,
    TENANT_PERMISSIONS.PRODUCTS_READ,
    TENANT_PERMISSIONS.PRODUCTS_WRITE,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_READ,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_WRITE,
    TENANT_PERMISSIONS.SUPPLIERS_READ,
    TENANT_PERMISSIONS.SUPPLIERS_WRITE,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_READ,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_WRITE,
    TENANT_PERMISSIONS.STOCK_READ,
    TENANT_PERMISSIONS.STOCK_CONSUME,
    TENANT_PERMISSIONS.STOCK_COUNT,
    TENANT_PERMISSIONS.STOCK_ADJUST,
    TENANT_PERMISSIONS.STOCK_MOVEMENTS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_READ,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CREATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_UPDATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_EXECUTE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_CANCEL,
    TENANT_PERMISSIONS.INVENTORY_USAGE_READ,
    TENANT_PERMISSIONS.INVENTORY_USAGE_RECORD,
    TENANT_PERMISSIONS.INVENTORY_USAGE_BULK_RECORD,
    TENANT_PERMISSIONS.INVENTORY_USAGE_REVERSE,
    TENANT_PERMISSIONS.INVENTORY_USAGE_REVIEW,
    TENANT_PERMISSIONS.INVENTORY_USAGE_CLOSE_PERIOD,
    TENANT_PERMISSIONS.INVENTORY_USAGE_MANAGE_TEMPLATES,
    TENANT_PERMISSIONS.INVENTORY_USAGE_RUN_SCHEDULED,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_READ,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_CREATE,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_SUBMIT,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_APPROVE,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_FULFILL,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_CANCEL,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_READ,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_CREATE,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_ALLOCATE,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_FULFILL,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_RELEASE,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_CANCEL,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_EXPIRE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_READ,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CREATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_UPDATE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_SUBMIT,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_APPROVE,
    TENANT_PERMISSIONS.PURCHASE_ORDERS_CANCEL,
    TENANT_PERMISSIONS.SHIPMENTS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_WRITE,
    TENANT_PERMISSIONS.SHIPMENTS_SEND,
    TENANT_PERMISSIONS.SHIPMENTS_RECEIVE,
    TENANT_PERMISSIONS.SHIPMENTS_FINALIZE,
    TENANT_PERMISSIONS.SHIPMENTS_AUTO_REORDER,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_READ,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_WRITE,
    TENANT_PERMISSIONS.ALERTS_READ,
    TENANT_PERMISSIONS.ALERTS_WRITE,
    TENANT_PERMISSIONS.REPORTS_READ,
    TENANT_PERMISSIONS.INSIGHTS_READ,
    TENANT_PERMISSIONS.OPERATIONAL_ACTION_CENTER_READ,
    TENANT_PERMISSIONS.PLATFORM_RELIABILITY_READ,
    TENANT_PERMISSIONS.TENANT_READ,
    TENANT_PERMISSIONS.USERS_READ,
    TENANT_PERMISSIONS.SYSTEM_STATUS_READ,
    TENANT_PERMISSIONS.SYSTEM_CONTEXT_READ,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_VIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_SUBMIT,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CANCEL,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_REVIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_EXECUTE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_READ,
    TENANT_PERMISSIONS.EXECUTION_TASKS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_ASSIGN,
    TENANT_PERMISSIONS.EXECUTION_TASKS_UPDATE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_CANCEL,
    TENANT_PERMISSIONS.EXECUTION_TASKS_COMPLETE,
    TENANT_PERMISSIONS.INVENTORY_OPTIMIZATION_READ,
    TENANT_PERMISSIONS.INVENTORY_OPTIMIZATION_CREATE,
    TENANT_PERMISSIONS.INVENTORY_OPTIMIZATION_GOVERN,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_VIEW,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_CREATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_UPDATE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_PAUSE,
    TENANT_PERMISSIONS.AUDIT_READ,
    TENANT_PERMISSIONS.PAR_LEVELS_READ,
    TENANT_PERMISSIONS.PAR_LEVELS_WRITE,
    TENANT_PERMISSIONS.CYCLE_COUNTS_READ,
    TENANT_PERMISSIONS.CYCLE_COUNTS_WRITE,
    TENANT_PERMISSIONS.CYCLE_COUNTS_APPROVE,
    TENANT_PERMISSIONS.REQUISITIONS_READ,
    TENANT_PERMISSIONS.REQUISITIONS_CREATE,
    TENANT_PERMISSIONS.APPROVAL_RULES_READ,
    TENANT_PERMISSIONS.APPROVALS_EXECUTE,
    TENANT_PERMISSIONS.SUPPLIER_CATALOG_READ,
    TENANT_PERMISSIONS.SUPPLIER_CATALOG_WRITE,
    TENANT_PERMISSIONS.INVOICES_READ,
    TENANT_PERMISSIONS.INVOICES_WRITE,
    TENANT_PERMISSIONS.ATTACHMENTS_READ,
    TENANT_PERMISSIONS.ATTACHMENTS_WRITE,
    TENANT_PERMISSIONS.NOTIFICATIONS_READ,
    TENANT_PERMISSIONS.NOTIFICATIONS_WRITE,
    TENANT_PERMISSIONS.BARCODE_LABELS_READ,
    TENANT_PERMISSIONS.BARCODE_LABELS_WRITE
  ]),

  staff: Object.freeze([
    TENANT_PERMISSIONS.DASHBOARD_READ,
    TENANT_PERMISSIONS.PRODUCTS_READ,
    TENANT_PERMISSIONS.PRODUCT_PACKAGES_READ,
    TENANT_PERMISSIONS.SUPPLIERS_READ,
    TENANT_PERMISSIONS.STORAGE_LOCATIONS_READ,
    TENANT_PERMISSIONS.STOCK_READ,
    TENANT_PERMISSIONS.STOCK_CONSUME,
    TENANT_PERMISSIONS.STOCK_COUNT,
    TENANT_PERMISSIONS.STOCK_MOVEMENTS_READ,
    TENANT_PERMISSIONS.INVENTORY_USAGE_READ,
    TENANT_PERMISSIONS.INVENTORY_USAGE_RECORD,
    TENANT_PERMISSIONS.INVENTORY_USAGE_BULK_RECORD,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_READ,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_CREATE,
    TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_SUBMIT,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_READ,
    TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_CREATE,
    TENANT_PERMISSIONS.STOCK_TRANSFERS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_READ,
    TENANT_PERMISSIONS.SHIPMENTS_RECEIVE,
    TENANT_PERMISSIONS.SHIPMENT_ITEMS_READ,
    TENANT_PERMISSIONS.ALERTS_READ,
    TENANT_PERMISSIONS.OPERATIONAL_ACTION_CENTER_READ,
    TENANT_PERMISSIONS.PLATFORM_RELIABILITY_READ,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_VIEW,
    TENANT_PERMISSIONS.EXECUTION_REQUESTS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_READ,
    TENANT_PERMISSIONS.EXECUTION_TASKS_CREATE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_UPDATE,
    TENANT_PERMISSIONS.EXECUTION_TASKS_COMPLETE,
    TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_VIEW,
    TENANT_PERMISSIONS.TENANT_READ,
    TENANT_PERMISSIONS.PAR_LEVELS_READ,
    TENANT_PERMISSIONS.CYCLE_COUNTS_READ,
    TENANT_PERMISSIONS.CYCLE_COUNTS_WRITE,
    TENANT_PERMISSIONS.REQUISITIONS_READ,
    TENANT_PERMISSIONS.REQUISITIONS_CREATE,
    TENANT_PERMISSIONS.NOTIFICATIONS_READ,
    TENANT_PERMISSIONS.BARCODE_LABELS_READ
  ])
});

export function getCurrentUserRole(): UserRole {
  const payload = decodeJwtPayload(getAccessToken());
  const role = payload?.role;

  if (role === 'admin' || role === 'manager' || role === 'staff') {
    return role;
  }

  return 'unknown';
}

export function permissionsForRole(role: UserRole = getCurrentUserRole()): readonly TenantPermission[] {
  if (role === 'admin' || role === 'manager' || role === 'staff') {
    return ROLE_PERMISSIONS[role];
  }

  return [];
}

export function hasPermission(permission: TenantPermission, role: UserRole = getCurrentUserRole()): boolean {
  return permissionsForRole(role).includes(permission);
}

export function hasAllPermissions(permissions: TenantPermission[], role: UserRole = getCurrentUserRole()): boolean {
  return permissions.every((permission) => hasPermission(permission, role));
}

export function hasAnyPermission(permissions: TenantPermission[], role: UserRole = getCurrentUserRole()): boolean {
  return permissions.some((permission) => hasPermission(permission, role));
}

export function hasAnyRole(allowedRoles: UserRole[]): boolean {
  const currentRole = getCurrentUserRole();
  return allowedRoles.includes(currentRole);
}

export function getRoleCapabilities(role: UserRole = getCurrentUserRole()) {
  const can = (permission: TenantPermission) => hasPermission(permission, role);

  return {
    role,
    isAdmin: role === 'admin',
    isManager: role === 'manager',
    isStaff: role === 'staff',
    canViewReports: can(TENANT_PERMISSIONS.REPORTS_READ),
    canViewInsights: can(TENANT_PERMISSIONS.INSIGHTS_READ),
    canViewOperationalActionCenter: can(TENANT_PERMISSIONS.OPERATIONAL_ACTION_CENTER_READ),
    canViewPlatformReliability: can(TENANT_PERMISSIONS.PLATFORM_RELIABILITY_READ),
    canViewUsers: can(TENANT_PERMISSIONS.USERS_READ),
    canManageUsers: can(TENANT_PERMISSIONS.USERS_WRITE),
    canViewAdminSystem: can(TENANT_PERMISSIONS.SYSTEM_STATUS_READ),
    canViewSystemContext: can(TENANT_PERMISSIONS.SYSTEM_CONTEXT_READ),
    canManageProducts: can(TENANT_PERMISSIONS.PRODUCTS_WRITE),
    canViewProductPackages: can(TENANT_PERMISSIONS.PRODUCT_PACKAGES_READ),
    canManageProductPackages: can(TENANT_PERMISSIONS.PRODUCT_PACKAGES_WRITE),
    canManageSuppliers: can(TENANT_PERMISSIONS.SUPPLIERS_WRITE),
    canManageStorageLocations: can(TENANT_PERMISSIONS.STORAGE_LOCATIONS_WRITE),
    canManageAlerts: can(TENANT_PERMISSIONS.ALERTS_WRITE),
    canOverrideAlerts: can(TENANT_PERMISSIONS.ALERTS_OVERRIDE),
    canManageShipments: can(TENANT_PERMISSIONS.SHIPMENTS_WRITE),
    canSendShipments: can(TENANT_PERMISSIONS.SHIPMENTS_SEND),
    canReceiveShipments: can(TENANT_PERMISSIONS.SHIPMENTS_RECEIVE),
    canFinalizeShipments: can(TENANT_PERMISSIONS.SHIPMENTS_FINALIZE),
    canAutoReorderShipments: can(TENANT_PERMISSIONS.SHIPMENTS_AUTO_REORDER),
    canViewShipmentItems: can(TENANT_PERMISSIONS.SHIPMENT_ITEMS_READ),
    canManageShipmentItems: can(TENANT_PERMISSIONS.SHIPMENT_ITEMS_WRITE),
    canConsumeStock: can(TENANT_PERMISSIONS.STOCK_CONSUME),
    canCountStock: can(TENANT_PERMISSIONS.STOCK_COUNT),
    canAdjustStock: can(TENANT_PERMISSIONS.STOCK_ADJUST),
    canViewInventoryUsage: can(TENANT_PERMISSIONS.INVENTORY_USAGE_READ),
    canRecordInventoryUsage: can(TENANT_PERMISSIONS.INVENTORY_USAGE_RECORD),
    canBulkRecordInventoryUsage: can(TENANT_PERMISSIONS.INVENTORY_USAGE_BULK_RECORD),
    canReverseInventoryUsage: can(TENANT_PERMISSIONS.INVENTORY_USAGE_REVERSE),
    canReviewInventoryUsage: can(TENANT_PERMISSIONS.INVENTORY_USAGE_REVIEW),
    canCloseInventoryUsagePeriods: can(TENANT_PERMISSIONS.INVENTORY_USAGE_CLOSE_PERIOD),
    canManageInventoryUsageTemplates: can(TENANT_PERMISSIONS.INVENTORY_USAGE_MANAGE_TEMPLATES),
    canRunScheduledInventoryUsage: can(TENANT_PERMISSIONS.INVENTORY_USAGE_RUN_SCHEDULED),
    canViewInventoryRequisitions: can(TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_READ),
    canCreateInventoryRequisitions: can(TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_CREATE),
    canSubmitInventoryRequisitions: can(TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_SUBMIT),
    canApproveInventoryRequisitions: can(TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_APPROVE),
    canFulfillInventoryRequisitions: can(TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_FULFILL),
    canCancelInventoryRequisitions: can(TENANT_PERMISSIONS.INVENTORY_REQUISITIONS_CANCEL),
    canViewInventoryReservations: can(TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_READ),
    canCreateInventoryReservations: can(TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_CREATE),
    canAllocateInventoryReservations: can(TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_ALLOCATE),
    canFulfillInventoryReservations: can(TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_FULFILL),
    canReleaseInventoryReservations: can(TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_RELEASE),
    canCancelInventoryReservations: can(TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_CANCEL),
    canExpireInventoryReservations: can(TENANT_PERMISSIONS.INVENTORY_RESERVATIONS_EXPIRE),
    canViewStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_READ),
    canCreateStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_CREATE),
    canUpdateStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_UPDATE),
    canExecuteStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_EXECUTE),
    canCancelStockTransfers: can(TENANT_PERMISSIONS.STOCK_TRANSFERS_CANCEL),
    canViewPurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_READ),
    canCreatePurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_CREATE),
    canUpdatePurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_UPDATE),
    canSubmitPurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_SUBMIT),
    canApprovePurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_APPROVE),
    canCancelPurchaseOrders: can(TENANT_PERMISSIONS.PURCHASE_ORDERS_CANCEL),
    canReadTenantSettings: can(TENANT_PERMISSIONS.TENANT_READ),
    canUpdateTenantSettings: can(TENANT_PERMISSIONS.TENANT_UPDATE),
    canDeleteTenantSettings: can(TENANT_PERMISSIONS.TENANT_DELETE),
    canViewExecutionRequests: can(TENANT_PERMISSIONS.EXECUTION_REQUESTS_VIEW),
    canCreateExecutionRequests: can(TENANT_PERMISSIONS.EXECUTION_REQUESTS_CREATE),
    canSubmitExecutionRequests: can(TENANT_PERMISSIONS.EXECUTION_REQUESTS_SUBMIT),
    canCancelExecutionRequests: can(TENANT_PERMISSIONS.EXECUTION_REQUESTS_CANCEL),
    canReviewExecutionRequests: can(TENANT_PERMISSIONS.EXECUTION_REQUESTS_REVIEW),
    canExecuteExecutionRequests: can(TENANT_PERMISSIONS.EXECUTION_REQUESTS_EXECUTE),
    canViewAutomationSchedules: can(TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_VIEW),
    canCreateAutomationSchedules: can(TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_CREATE),
    canUpdateAutomationSchedules: can(TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_UPDATE),
    canPauseAutomationSchedules: can(TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_PAUSE),
    canResumeAutomationSchedules: can(TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_RESUME),
    canDisableAutomationSchedules: can(TENANT_PERMISSIONS.AUTOMATION_SCHEDULES_DISABLE),
    canViewSessions: role === 'admin' || role === 'manager' || role === 'staff',
    canViewTenantDiagnostics: can(TENANT_PERMISSIONS.TENANT_DIAGNOSTICS_READ),
    canGovernInventoryOptimization: can(TENANT_PERMISSIONS.INVENTORY_OPTIMIZATION_GOVERN),
    canViewAudit: can(TENANT_PERMISSIONS.AUDIT_READ)
  };
}
