import { getPlatformAccessToken } from './platformAuth';
import type { PlatformRole } from './platformAuth';

export const PLATFORM_PERMISSIONS = Object.freeze({
  PLATFORM_DASHBOARD_READ: 'platform.dashboard.read',
  TENANTS_READ: 'platform.tenants.read',
  TENANTS_CREATE: 'platform.tenants.create',
  TENANTS_UPDATE: 'platform.tenants.update',
  TENANTS_LOCK: 'platform.tenants.lock',
  TENANTS_UNLOCK: 'platform.tenants.unlock',
  TENANTS_EXPORT: 'platform.tenants.export',
  SYSTEM_HEALTH_READ: 'platform.system_health.read',
  DIAGNOSTICS_READ: 'platform.diagnostics.read',
  PLATFORM_USERS_READ: 'platform.users.read',
  PLATFORM_USERS_WRITE: 'platform.users.write',
  PLATFORM_SESSIONS_READ: 'platform.sessions.read',
  PLATFORM_SESSIONS_REVOKE: 'platform.sessions.revoke',
  PLATFORM_NOTIFICATIONS_READ: 'platform.notifications.read',
  PLATFORM_NOTIFICATIONS_WRITE: 'platform.notifications.write',
  PLATFORM_BILLING_READ: 'platform.billing.read',
  PLATFORM_BILLING_WRITE: 'platform.billing.write',
  PLATFORM_SECURITY_READ: 'platform.security.read',
  PLATFORM_SECURITY_WRITE: 'platform.security.write',
  PLATFORM_MAINTENANCE_READ: 'platform.maintenance.read',
  PLATFORM_MAINTENANCE_WRITE: 'platform.maintenance.write',
  PLATFORM_ANNOUNCEMENTS_READ: 'platform.announcements.read',
  PLATFORM_ANNOUNCEMENTS_WRITE: 'platform.announcements.write',
  PLATFORM_INCIDENTS_READ: 'platform.incidents.read',
  PLATFORM_INCIDENTS_WRITE: 'platform.incidents.write',
  PLATFORM_DATA_RETENTION_READ: 'platform.data_retention.read',
  PLATFORM_DATA_RETENTION_WRITE: 'platform.data_retention.write',
  PLATFORM_SLA_READ: 'platform.sla.read',
  PLATFORM_SLA_WRITE: 'platform.sla.write',
  PLATFORM_RUNBOOKS_READ: 'platform.runbooks.read',
  PLATFORM_RUNBOOKS_WRITE: 'platform.runbooks.write',
  PLATFORM_RUNBOOKS_EXECUTE: 'platform.runbooks.execute',
  PLATFORM_CHANGES_READ: 'platform.changes.read',
  PLATFORM_CHANGES_WRITE: 'platform.changes.write',
  PLATFORM_CHANGES_APPROVE: 'platform.changes.approve',
  PLATFORM_CHANGES_EXECUTE: 'platform.changes.execute',
  PLATFORM_API_KEYS_READ: 'platform.api_keys.read',
  PLATFORM_API_KEYS_WRITE: 'platform.api_keys.write',
  PLATFORM_WEBHOOKS_READ: 'platform.webhooks.read',
  PLATFORM_WEBHOOKS_WRITE: 'platform.webhooks.write',
  PLATFORM_ACCESS_REVIEWS_READ: 'platform.access_reviews.read',
  PLATFORM_ACCESS_REVIEWS_WRITE: 'platform.access_reviews.write',
  PLATFORM_COMPLIANCE_READ: 'platform.compliance.read',
  PLATFORM_COMPLIANCE_WRITE: 'platform.compliance.write',
  PLATFORM_PRIVACY_READ: 'platform.privacy.read',
  PLATFORM_PRIVACY_WRITE: 'platform.privacy.write',
  PLATFORM_VENDORS_READ: 'platform.vendors.read',
  PLATFORM_VENDORS_WRITE: 'platform.vendors.write',
  PLATFORM_DEPENDENCIES_READ: 'platform.dependencies.read',
  PLATFORM_DEPENDENCIES_WRITE: 'platform.dependencies.write',
  PLATFORM_RELEASES_READ: 'platform.releases.read',
  PLATFORM_RELEASES_WRITE: 'platform.releases.write',
  PLATFORM_RISKS_READ: 'platform.risks.read',
  PLATFORM_RISKS_WRITE: 'platform.risks.write',
  PLATFORM_CAPACITY_READ: 'platform.capacity.read',
  PLATFORM_CAPACITY_WRITE: 'platform.capacity.write',
  PLATFORM_JOBS_READ: 'platform.jobs.read',
  PLATFORM_JOBS_WRITE: 'platform.jobs.write',
  SUPPORT_SESSION_READ: 'platform.support_sessions.read',
  SUPPORT_SESSION_START: 'platform.support_sessions.start',
  SUPPORT_SESSION_END: 'platform.support_sessions.end',
  SUPPORT_SESSION_APPROVE: 'platform.support_sessions.approve',
  AUDIT_READ: 'platform.audit.read'
} as const);

export type PlatformPermission = (typeof PLATFORM_PERMISSIONS)[keyof typeof PLATFORM_PERMISSIONS];

type PlatformJwtPayload = { typ?: string; role?: string; id?: string; exp?: number };
function decodeJwtPayload(token: string | null): PlatformJwtPayload | null {
  if (!token) return null;
  try { const parts = token.split('.'); if (parts.length !== 3) return null; const base64 = parts[1].replace(/-/g, '+').replace(/_/g, '/'); const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, '='); return JSON.parse(atob(padded)) as PlatformJwtPayload; } catch { return null; }
}

const ALL = Object.values(PLATFORM_PERMISSIONS);
export const PLATFORM_ROLE_PERMISSIONS: Record<Exclude<PlatformRole, 'unknown'>, readonly PlatformPermission[]> = Object.freeze({
  superadmin: ALL,
  support: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.SYSTEM_HEALTH_READ, PLATFORM_PERMISSIONS.DIAGNOSTICS_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.PLATFORM_MAINTENANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_ANNOUNCEMENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_READ, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_READ, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_READ, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_START, PLATFORM_PERMISSIONS.SUPPORT_SESSION_END, PLATFORM_PERMISSIONS.SUPPORT_SESSION_APPROVE],
  support_l1: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.PLATFORM_MAINTENANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_ANNOUNCEMENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_READ, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_READ, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_READ, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_START],
  support_l2: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.SYSTEM_HEALTH_READ, PLATFORM_PERMISSIONS.DIAGNOSTICS_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.PLATFORM_MAINTENANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_ANNOUNCEMENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_READ, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_READ, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_READ, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_START, PLATFORM_PERMISSIONS.SUPPORT_SESSION_END, PLATFORM_PERMISSIONS.SUPPORT_SESSION_APPROVE],
  security: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.SYSTEM_HEALTH_READ, PLATFORM_PERMISSIONS.DIAGNOSTICS_READ, PLATFORM_PERMISSIONS.PLATFORM_USERS_READ, PLATFORM_PERMISSIONS.PLATFORM_SESSIONS_READ, PLATFORM_PERMISSIONS.PLATFORM_SESSIONS_REVOKE, PLATFORM_PERMISSIONS.PLATFORM_SECURITY_READ, PLATFORM_PERMISSIONS.PLATFORM_SECURITY_WRITE, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.AUDIT_READ],
  billing: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.TENANTS_UPDATE, PLATFORM_PERMISSIONS.PLATFORM_BILLING_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.AUDIT_READ],
  ops: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.TENANTS_UPDATE, PLATFORM_PERMISSIONS.TENANTS_LOCK, PLATFORM_PERMISSIONS.TENANTS_UNLOCK, PLATFORM_PERMISSIONS.TENANTS_EXPORT, PLATFORM_PERMISSIONS.PLATFORM_BILLING_READ, PLATFORM_PERMISSIONS.PLATFORM_BILLING_WRITE, PLATFORM_PERMISSIONS.SYSTEM_HEALTH_READ, PLATFORM_PERMISSIONS.DIAGNOSTICS_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_MAINTENANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_MAINTENANCE_WRITE, PLATFORM_PERMISSIONS.PLATFORM_ANNOUNCEMENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_ANNOUNCEMENTS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_READ, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_WRITE, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_WRITE, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_READ, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_WRITE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_APPROVE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_READ, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_READ, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_WRITE, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_WRITE, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_WRITE, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_WRITE, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_WRITE, PLATFORM_PERMISSIONS.PLATFORM_RISKS_WRITE, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_WRITE, PLATFORM_PERMISSIONS.PLATFORM_SECURITY_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_START, PLATFORM_PERMISSIONS.SUPPORT_SESSION_END, PLATFORM_PERMISSIONS.SUPPORT_SESSION_APPROVE, PLATFORM_PERMISSIONS.AUDIT_READ],
  tenant_success: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.TENANTS_CREATE, PLATFORM_PERMISSIONS.TENANTS_UPDATE, PLATFORM_PERMISSIONS.PLATFORM_BILLING_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.PLATFORM_MAINTENANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_ANNOUNCEMENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_READ, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_READ, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_READ, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_START, PLATFORM_PERMISSIONS.AUDIT_READ],
  readonly_audit: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.PLATFORM_BILLING_READ, PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATIONS_READ, PLATFORM_PERMISSIONS.PLATFORM_MAINTENANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_ANNOUNCEMENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_READ, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_READ, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_READ, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_READ, PLATFORM_PERMISSIONS.AUDIT_READ],
  platform_viewer: [PLATFORM_PERMISSIONS.PLATFORM_DASHBOARD_READ, PLATFORM_PERMISSIONS.TENANTS_READ, PLATFORM_PERMISSIONS.SYSTEM_HEALTH_READ, PLATFORM_PERMISSIONS.DIAGNOSTICS_READ, PLATFORM_PERMISSIONS.PLATFORM_INCIDENTS_READ, PLATFORM_PERMISSIONS.PLATFORM_DATA_RETENTION_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_SLA_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_EXECUTE, PLATFORM_PERMISSIONS.PLATFORM_CHANGES_READ, PLATFORM_PERMISSIONS.PLATFORM_API_KEYS_READ, PLATFORM_PERMISSIONS.PLATFORM_WEBHOOKS_READ, PLATFORM_PERMISSIONS.PLATFORM_ACCESS_REVIEWS_READ, PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ, PLATFORM_PERMISSIONS.PLATFORM_PRIVACY_READ, PLATFORM_PERMISSIONS.PLATFORM_VENDORS_READ, PLATFORM_PERMISSIONS.PLATFORM_DEPENDENCIES_READ, PLATFORM_PERMISSIONS.PLATFORM_RELEASES_READ, PLATFORM_PERMISSIONS.PLATFORM_RISKS_READ, PLATFORM_PERMISSIONS.PLATFORM_CAPACITY_READ, PLATFORM_PERMISSIONS.SUPPORT_SESSION_READ, PLATFORM_PERMISSIONS.AUDIT_READ]
});
export function getCurrentPlatformRoleFromToken(): PlatformRole { const payload = decodeJwtPayload(getPlatformAccessToken()); const role = payload?.role; if (payload?.typ !== 'platform') return 'unknown'; if (role === 'superadmin' || role === 'support' || role === 'platform_viewer' || role === 'support_l1' || role === 'support_l2' || role === 'security' || role === 'billing' || role === 'ops' || role === 'tenant_success' || role === 'readonly_audit') return role; return 'unknown'; }
export function platformPermissionsForRole(role: PlatformRole = getCurrentPlatformRoleFromToken()): readonly PlatformPermission[] { return role !== 'unknown' ? PLATFORM_ROLE_PERMISSIONS[role] || [] : []; }
export function hasPlatformPermission(permission: PlatformPermission, role: PlatformRole = getCurrentPlatformRoleFromToken()): boolean { return platformPermissionsForRole(role).includes(permission); }
export function hasAllPlatformPermissions(permissions: PlatformPermission[], role: PlatformRole = getCurrentPlatformRoleFromToken()): boolean { return permissions.every((permission) => hasPlatformPermission(permission, role)); }
export function hasAnyPlatformPermission(permissions: PlatformPermission[], role: PlatformRole = getCurrentPlatformRoleFromToken()): boolean { return permissions.some((permission) => hasPlatformPermission(permission, role)); }
