import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '../lib/api';
import { hasPermission, TENANT_PERMISSIONS } from '../lib/permissions';

type Customer={id:string;name:string;email?:string|null;phone?:string|null;address?:string|null};
type Product={id:string;name:string;unit:string}; type Location={id:string;name:string};
type OrderItem={id:string;product_name:string;product_unit:string;storage_location_name:string;quantity:number|string;dispatched_quantity:number|string};
type Order={id:string;order_number:string;customer_name:string;status:string;requested_date?:string|null;notes?:string|null;items:OrderItem[];version:number};
type Line={product_id:string;storage_location_id:string;quantity:string};
const box={background:'#fff',border:'1px solid #e5e7eb',borderRadius:12,padding:18,marginBottom:16} as const; const input={padding:'9px 10px',border:'1px solid #d1d5db',borderRadius:8,width:'100%',boxSizing:'border-box'} as const; const button={padding:'9px 12px',borderRadius:8,border:'1px solid #cbd5e1',cursor:'pointer',background:'#fff'} as const;
export default function OutboundPage(){
 const qc=useQueryClient(); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 const canCustomerWrite=hasPermission(TENANT_PERMISSIONS.CUSTOMERS_WRITE); const canCreate=hasPermission(TENANT_PERMISSIONS.OUTBOUND_ORDERS_CREATE); const canUpdate=hasPermission(TENANT_PERMISSIONS.OUTBOUND_ORDERS_UPDATE); const canDispatch=hasPermission(TENANT_PERMISSIONS.OUTBOUND_ORDERS_DISPATCH); const canCancel=hasPermission(TENANT_PERMISSIONS.OUTBOUND_ORDERS_CANCEL);
 const customers=useQuery({queryKey:['outbound-customers'],queryFn:()=>apiRequest<Customer[]>('/outbound/customers')}); const orders=useQuery({queryKey:['outbound-orders'],queryFn:()=>apiRequest<Order[]>('/outbound/orders')}); const products=useQuery({queryKey:['products'],queryFn:()=>apiRequest<Product[]>('/products')}); const locations=useQuery({queryKey:['storage-locations'],queryFn:()=>apiRequest<Location[]>('/storage-locations')});
 const [customerForm,setCustomerForm]=useState({name:'',email:'',phone:'',address:''}); const [orderForm,setOrderForm]=useState<{customer_id:string;requested_date:string;notes:string;items:Line[]}>({customer_id:'',requested_date:'',notes:'',items:[{product_id:'',storage_location_id:'',quantity:'1'}]});
 const invalidate=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['outbound-customers']}),qc.invalidateQueries({queryKey:['outbound-orders']}),qc.invalidateQueries({queryKey:['stock']}),qc.invalidateQueries({queryKey:['inventory-lots']})]);};
 const mutation=useMutation({mutationFn:({path,body,version}:{path:string;body?:unknown;version?:number})=>apiRequest(path,{method:'POST',headers:version===undefined?undefined:{'If-Match-Version':String(version)},body:JSON.stringify(body??{})}),onSuccess:async()=>{setError('');setMessage('Saved.');await invalidate();},onError:e=>{setMessage('');setError(e instanceof Error?e.message:'Action failed');}});
 const createCustomer=()=>{if(!customerForm.name.trim())return; mutation.mutate({path:'/outbound/customers',body:{...customerForm,email:customerForm.email||null,phone:customerForm.phone||null,address:customerForm.address||null}}); setCustomerForm({name:'',email:'',phone:'',address:''});};
 const createOrder=()=>{const items=orderForm.items.filter(x=>x.product_id&&x.storage_location_id&&Number(x.quantity)>0).map(x=>({...x,quantity:Number(x.quantity)})); if(!orderForm.customer_id||!items.length){setError('Choose a customer and at least one complete line.');return;} mutation.mutate({path:'/outbound/orders',body:{...orderForm,requested_date:orderForm.requested_date||null,notes:orderForm.notes||null,items}});};
 const customerOptions=customers.data??[]; const orderRows=orders.data??[]; const productOptions=products.data??[]; const locationOptions=locations.data??[]; const openCount=orderRows.filter(o=>!['dispatched','cancelled'].includes(o.status)).length;
 return <div style={{display:'grid',gap:16}}><section style={box}><h2 style={{marginTop:0}}>Outbound</h2><p style={{marginBottom:0}}>Manage customers and move customer orders through Confirm → Picking → Packed → Dispatch. Dispatch removes stock using the existing oldest-expiry-first stock rules.</p><div style={{marginTop:8,fontWeight:700}}>Open orders: {openCount}</div>{message?<div style={{marginTop:10,color:'#166534'}}>{message}</div>:null}{error?<div style={{marginTop:10,color:'#991b1b'}}>{error}</div>:null}</section>
 <section style={box}><h3 style={{marginTop:0}}>Customers</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><input style={input} placeholder="Customer name" value={customerForm.name} onChange={e=>setCustomerForm({...customerForm,name:e.target.value})}/><input style={input} placeholder="Email" value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})}/><input style={input} placeholder="Phone" value={customerForm.phone} onChange={e=>setCustomerForm({...customerForm,phone:e.target.value})}/><input style={input} placeholder="Address" value={customerForm.address} onChange={e=>setCustomerForm({...customerForm,address:e.target.value})}/></div>{canCustomerWrite?<button style={{...button,marginTop:10}} onClick={createCustomer}>Add Customer</button>:null}<div style={{marginTop:12}}>{customerOptions.map(c=><span key={c.id} style={{display:'inline-block',marginRight:8,marginBottom:8,padding:'6px 8px',border:'1px solid #e5e7eb',borderRadius:8}}>{c.name}</span>)}</div></section>
 <section style={box}><h3 style={{marginTop:0}}>Create customer order</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:10}}><select style={input} value={orderForm.customer_id} onChange={e=>setOrderForm({...orderForm,customer_id:e.target.value})}><option value="">Choose customer</option>{customerOptions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input style={input} type="date" value={orderForm.requested_date} onChange={e=>setOrderForm({...orderForm,requested_date:e.target.value})}/><input style={input} placeholder="Notes" value={orderForm.notes} onChange={e=>setOrderForm({...orderForm,notes:e.target.value})}/></div>{orderForm.items.map((line,index)=><div key={index} style={{display:'grid',gridTemplateColumns:'2fr 2fr 1fr auto',gap:8,marginTop:10}}><select style={input} value={line.product_id} onChange={e=>setOrderForm({...orderForm,items:orderForm.items.map((x,i)=>i===index?{...x,product_id:e.target.value}:x)})}><option value="">Product</option>{productOptions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select style={input} value={line.storage_location_id} onChange={e=>setOrderForm({...orderForm,items:orderForm.items.map((x,i)=>i===index?{...x,storage_location_id:e.target.value}:x)})}><option value="">Location</option>{locationOptions.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><input style={input} type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={e=>setOrderForm({...orderForm,items:orderForm.items.map((x,i)=>i===index?{...x,quantity:e.target.value}:x)})}/><button style={button} onClick={()=>setOrderForm({...orderForm,items:orderForm.items.filter((_,i)=>i!==index)})}>Remove</button></div>)}<div style={{display:'flex',gap:8,marginTop:10}}><button style={button} onClick={()=>setOrderForm({...orderForm,items:[...orderForm.items,{product_id:'',storage_location_id:'',quantity:'1'}]})}>Add line</button>{canCreate?<button style={button} onClick={createOrder}>Create Order</button>:null}</div></section>
 <section style={box}><h3 style={{marginTop:0}}>Orders</h3>{orderRows.length===0?<p>No customer orders yet.</p>:orderRows.map(o=><div key={o.id} style={{borderTop:'1px solid #e5e7eb',padding:'12px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><strong>{o.order_number} · {o.customer_name}</strong><span>{o.status}</span></div><div style={{marginTop:6,fontSize:14}}>{o.items.map(i=>`${i.product_name} ${i.quantity} ${i.product_unit} from ${i.storage_location_name}`).join(' · ')}</div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:8}}>{o.status==='draft'&&canUpdate?<button style={button} onClick={()=>mutation.mutate({path:`/outbound/orders/${o.id}/confirm`,version:Number(o.version)})}>Confirm</button>:null}{o.status==='confirmed'&&canUpdate?<button style={button} onClick={()=>mutation.mutate({path:`/outbound/orders/${o.id}/start-picking`,version:Number(o.version)})}>Start Picking</button>:null}{o.status==='picking'&&canUpdate?<button style={button} onClick={()=>mutation.mutate({path:`/outbound/orders/${o.id}/mark-packed`,version:Number(o.version)})}>Mark Packed</button>:null}{o.status==='packed'&&canDispatch?<button style={button} onClick={()=>{if(window.confirm('Dispatch this order and remove its stock?'))mutation.mutate({path:`/outbound/orders/${o.id}/dispatch`,version:Number(o.version)});}}>Dispatch</button>:null}{!['dispatched','cancelled'].includes(o.status)&&canCancel?<button style={button} onClick={()=>{const reason=window.prompt('Cancellation reason');if(reason&&reason.trim().length>=3)mutation.mutate({path:`/outbound/orders/${o.id}/cancel`,body:{reason:reason.trim()},version:Number(o.version)});}}>Cancel</button>:null}</div></div>)}</section></div>;
}
