import { useQuery } from '@tanstack/react-query';
import type { CSSProperties } from 'react';
import { platformApiRequest } from '../lib/platformApi';

type CustomerSuccessItem = { tenant_id: string; tenant_name: string; tenant_status: string; billing_status: string; plan_code?: string | null; primary_contacts: number; open_tasks: number; open_urgent_tasks: number; overdue_tasks: number; unresolved_follow_ups: number; days_since_last_touch?: number | null; open_support_sessions: number; open_incidents: number; subscription_readiness_state: string; license_enforcement_state: string; success_risk_score: number; customer_success_state: string; risk_flags: { code: string; severity: string; points: number; message: string }[]; recommended_admin_actions: string[] };
type CustomerSuccessPackage = { posture: string; health_states: string[]; summary: Record<string, number>; items: CustomerSuccessItem[] };

function badgeStyle(value: string): CSSProperties { if (value.includes('risk')) return { ...styles.badge, background: '#fee2e2', color: '#991b1b' }; if (value.includes('watch')) return { ...styles.badge, background: '#fef3c7', color: '#92400e' }; return { ...styles.badge, background: '#dcfce7', color: '#166534' }; }
function Chips({ values }: { values: string[] }) { return <div style={styles.flags}>{values.length ? values.map((value) => <span key={value} style={styles.flag}>{value}</span>) : <span style={styles.help}>None</span>}</div>; }

export default function PlatformCustomerSuccessAdminPage() {
  const successQuery = useQuery({ queryKey: ['platform', 'customer-success-admin'], queryFn: () => platformApiRequest<CustomerSuccessPackage>('/platform/customer-success-admin') });
  const data = successQuery.data;
  const summary = data?.summary || {};
  const items = data?.items || [];
  const metrics = ['tenants_reviewed', 'ready_tenants', 'watch_tenants', 'at_risk_tenants', 'tenants_missing_primary_contact', 'tenants_with_overdue_tasks', 'tenants_with_unresolved_follow_ups', 'tenants_with_support_escalations'];

  return <div style={styles.page}>
    <header style={styles.header}><div><h1 style={styles.title}>Customer success admin</h1><p style={styles.subtitle}>Commercial admin cockpit for tenant success risk, lifecycle blockers, contacts, communications, support escalations, and recommended admin actions.</p></div>{data ? <span style={badgeStyle(data.posture)}>{data.posture}</span> : null}</header>
    {successQuery.isLoading ? <section style={styles.card}>Loading customer success admin tooling…</section> : null}
    {successQuery.error ? <section style={styles.card}>Unable to load customer success admin tooling.</section> : null}
    {data ? <section style={styles.summaryGrid}>{metrics.map((key) => <div key={key} style={styles.card}><strong>{key.replaceAll('_', ' ')}</strong><div style={styles.metric}>{summary[key] ?? 0}</div></div>)}</section> : null}
    {data ? <section style={styles.card}><h2 style={styles.cardTitle}>Health states</h2><Chips values={data.health_states} /></section> : null}
    <section style={styles.card}><h2 style={styles.cardTitle}>Tenant customer success evidence</h2><div style={styles.tableWrap}><table style={styles.table}><thead><tr><th style={styles.th}>Tenant</th><th style={styles.th}>Commercial state</th><th style={styles.th}>Contacts & tasks</th><th style={styles.th}>Touch & support</th><th style={styles.th}>Risk</th><th style={styles.th}>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.tenant_id}><td style={styles.td}><strong>{item.tenant_name}</strong><br /><span style={styles.help}>{item.tenant_status} · {item.customer_success_state}</span></td><td style={styles.td}>{item.billing_status}<br /><span style={styles.help}>{item.plan_code || '—'} · {item.subscription_readiness_state} · {item.license_enforcement_state}</span></td><td style={styles.td}>Contacts: {item.primary_contacts}<br /><span style={styles.help}>Open: {item.open_tasks}, urgent: {item.open_urgent_tasks}, overdue: {item.overdue_tasks}</span></td><td style={styles.td}>Last touch: {item.days_since_last_touch ?? '—'} days<br /><span style={styles.help}>Follow-ups: {item.unresolved_follow_ups}, support: {item.open_support_sessions}, incidents: {item.open_incidents}</span></td><td style={styles.td}><strong>{item.success_risk_score}</strong><br /><Chips values={item.risk_flags.map((flag) => flag.code)} /></td><td style={styles.td}><Chips values={item.recommended_admin_actions} /></td></tr>)}{!items.length ? <tr><td style={styles.td} colSpan={6}>No customer success admin rows available.</td></tr> : null}</tbody></table></div></section>
  </div>;
}

const styles: Record<string, CSSProperties> = { page: { display: 'flex', flexDirection: 'column', gap: 20 }, header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 }, title: { margin: 0, fontSize: 28 }, subtitle: { margin: '6px 0 0', color: '#6b7280' }, badge: { padding: '8px 12px', borderRadius: 999, fontWeight: 700, whiteSpace: 'nowrap' }, summaryGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12 }, card: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 14, padding: 18, boxShadow: '0 1px 2px rgba(0,0,0,0.04)' }, metric: { fontSize: 28, fontWeight: 800, marginTop: 8 }, cardTitle: { margin: '0 0 10px', fontSize: 18 }, flags: { display: 'flex', flexWrap: 'wrap', gap: 6 }, flag: { background: '#eef2ff', color: '#3730a3', padding: '4px 8px', borderRadius: 999, fontSize: 12, fontWeight: 700 }, help: { color: '#6b7280', fontSize: 12 }, tableWrap: { overflowX: 'auto' }, table: { width: '100%', borderCollapse: 'collapse' }, th: { textAlign: 'left', borderBottom: '1px solid #e5e7eb', padding: '10px 8px', color: '#374151', fontSize: 13 }, td: { borderBottom: '1px solid #f3f4f6', padding: '12px 8px', verticalAlign: 'top' } };
