import type { CSSProperties } from 'react';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { platformApiRequest } from '../lib/platformApi';
import { hasPlatformPermission, PLATFORM_PERMISSIONS } from '../lib/platformPermissions';

type PlatformUser = { id: string; email: string };
type Runbook = { id: string; title: string };
type Job = {
  id: string; name: string; job_key: string; category: string; status: string; schedule_label?: string | null;
  owner_platform_user_id?: string | null; owner_email?: string | null; runbook_id?: string | null; runbook_title?: string | null;
  last_run_at?: string | null; last_status?: string | null; last_duration_ms?: number | null; last_error?: string | null; next_run_at?: string | null;
  consecutive_failures: number; failure_threshold: number; overdue?: boolean; failing_attention?: boolean; notes?: string | null; updated_at: string;
};
type JobsResponse = { jobs: Job[]; summary: { total: number; overdue: number; failing: number; last_failed: number; by_status: Record<string, number>; by_category: Record<string, number> }; categories: string[]; statuses: string[]; run_statuses: string[] };

const emptyForm = { name: '', job_key: '', category: 'operational', status: 'enabled', schedule_label: '', owner_platform_user_id: '', next_run_at: '', failure_threshold: '3', runbook_id: '', notes: '' };
type JobForm = typeof emptyForm;
const runFormDefault = { last_status: 'success', last_duration_ms: '', last_error: '', next_run_at: '' };

function label(value?: string | null) { return value ? value.replace(/_/g, ' ') : '—'; }
function dateTime(value?: string | null) { return value ? new Date(value).toLocaleString() : '—'; }
function toInputDateTime(value?: string | null) { return value ? new Date(value).toISOString().slice(0, 16) : ''; }
function statusStyle(job: Job): CSSProperties { if (job.status === 'archived') return styles.badgeMuted; if (job.status === 'degraded' || job.failing_attention || job.last_status === 'failed') return styles.badgeDanger; if (job.status === 'paused' || job.overdue) return styles.badgeWarn; return styles.badgeGood; }
function toForm(job: Job): JobForm { return { name: job.name || '', job_key: job.job_key || '', category: job.category || 'operational', status: job.status || 'enabled', schedule_label: job.schedule_label || '', owner_platform_user_id: job.owner_platform_user_id || '', next_run_at: toInputDateTime(job.next_run_at), failure_threshold: String(job.failure_threshold || 3), runbook_id: job.runbook_id || '', notes: job.notes || '' }; }
function payload(form: JobForm) { return { name: form.name, job_key: form.job_key, category: form.category, status: form.status, schedule_label: form.schedule_label || null, owner_platform_user_id: form.owner_platform_user_id || null, next_run_at: form.next_run_at ? new Date(form.next_run_at).toISOString() : null, failure_threshold: Number(form.failure_threshold || 3), runbook_id: form.runbook_id || null, notes: form.notes || null }; }

export default function PlatformOperationalJobsPage() {
  const queryClient = useQueryClient();
  const canWrite = hasPlatformPermission(PLATFORM_PERMISSIONS.PLATFORM_JOBS_WRITE);
  const canReadUsers = hasPlatformPermission(PLATFORM_PERMISSIONS.PLATFORM_USERS_READ);
  const canReadRunbooks = hasPlatformPermission(PLATFORM_PERMISSIONS.PLATFORM_RUNBOOKS_READ);
  const [filters, setFilters] = useState({ category: '', status: '', search: '', attention_only: true, include_archived: false });
  const [form, setForm] = useState<JobForm>(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [runJobId, setRunJobId] = useState<string | null>(null);
  const [runForm, setRunForm] = useState(runFormDefault);

  const queryString = useMemo(() => { const params = new URLSearchParams(); if (filters.category) params.set('category', filters.category); if (filters.status) params.set('status', filters.status); if (filters.search) params.set('search', filters.search); if (filters.attention_only) params.set('attention_only', 'true'); if (filters.include_archived) params.set('include_archived', 'true'); params.set('limit', '300'); return params.toString(); }, [filters]);
  const jobs = useQuery({ queryKey: ['platform', 'operational-jobs', filters], queryFn: () => platformApiRequest<JobsResponse>(`/platform/operational-jobs?${queryString}`) });
  const users = useQuery({ queryKey: ['platform', 'jobs-users'], queryFn: () => platformApiRequest<PlatformUser[]>('/platform/users'), enabled: canWrite && canReadUsers });
  const runbooks = useQuery({ queryKey: ['platform', 'jobs-runbooks'], queryFn: () => platformApiRequest<{ runbooks: Runbook[] }>('/platform/runbooks?limit=500'), enabled: canWrite && canReadRunbooks });

  const save = useMutation({ mutationFn: () => { const body = JSON.stringify(payload(form)); return editingId ? platformApiRequest(`/platform/operational-jobs/${editingId}`, { method: 'PATCH', body }) : platformApiRequest('/platform/operational-jobs', { method: 'POST', body }); }, onSuccess: async () => { setForm(emptyForm); setEditingId(null); await queryClient.invalidateQueries({ queryKey: ['platform', 'operational-jobs'] }); } });
  const recordRun = useMutation({ mutationFn: () => platformApiRequest(`/platform/operational-jobs/${runJobId}/runs`, { method: 'POST', body: JSON.stringify({ last_status: runForm.last_status, last_duration_ms: runForm.last_duration_ms ? Number(runForm.last_duration_ms) : null, last_error: runForm.last_error || null, next_run_at: runForm.next_run_at ? new Date(runForm.next_run_at).toISOString() : null }) }), onSuccess: async () => { setRunJobId(null); setRunForm(runFormDefault); await queryClient.invalidateQueries({ queryKey: ['platform', 'operational-jobs'] }); } });
  const archive = useMutation({ mutationFn: (id: string) => platformApiRequest(`/platform/operational-jobs/${id}/archive`, { method: 'POST', body: JSON.stringify({}) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['platform', 'operational-jobs'] }) });

  const response = jobs.data;
  const categories = response?.categories || ['backup','billing','notification','webhook','retention','health_scan','sla_scan','maintenance','reporting','operational','other'];
  const statuses = response?.statuses || ['enabled','paused','degraded','disabled','archived'];
  const rows = response?.jobs || [];
  const summary = response?.summary;

  return (
    <div style={styles.page}>
      <header style={styles.header}><div><h1 style={styles.title}>Operational jobs</h1><p style={styles.subtitle}>Track recurring platform work such as backups, retention scans, billing syncs, webhook delivery, health scans, and SLA checks.</p></div></header>
      <section style={styles.metrics}><div style={styles.metric}><strong>{summary?.total ?? 0}</strong><span>Total shown</span></div><div style={styles.metric}><strong>{summary?.overdue ?? 0}</strong><span>Overdue</span></div><div style={styles.metric}><strong>{summary?.failing ?? 0}</strong><span>Failing threshold</span></div><div style={styles.metric}><strong>{summary?.last_failed ?? 0}</strong><span>Last run failed</span></div></section>
      <section style={styles.panel}><h2 style={styles.sectionTitle}>Filters</h2><div style={styles.grid4}><select value={filters.category} onChange={(event) => setFilters((prev) => ({ ...prev, category: event.target.value }))} style={styles.input}><option value="">All categories</option>{categories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><select value={filters.status} onChange={(event) => setFilters((prev) => ({ ...prev, status: event.target.value }))} style={styles.input}><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><input value={filters.search} onChange={(event) => setFilters((prev) => ({ ...prev, search: event.target.value }))} placeholder="Search jobs" style={styles.input} /><label style={styles.checkRow}><input type="checkbox" checked={filters.attention_only} onChange={(event) => setFilters((prev) => ({ ...prev, attention_only: event.target.checked }))} /> Attention only</label><label style={styles.checkRow}><input type="checkbox" checked={filters.include_archived} onChange={(event) => setFilters((prev) => ({ ...prev, include_archived: event.target.checked }))} /> Include archived</label></div></section>
      {canWrite ? <section style={styles.panel}><h2 style={styles.sectionTitle}>{editingId ? 'Edit job' : 'Add job'}</h2><div style={styles.grid3}><input value={form.name} onChange={(event) => setForm((prev) => ({ ...prev, name: event.target.value }))} placeholder="Job name" style={styles.input} /><input value={form.job_key} onChange={(event) => setForm((prev) => ({ ...prev, job_key: event.target.value }))} placeholder="job.key" style={styles.input} /><input value={form.schedule_label} onChange={(event) => setForm((prev) => ({ ...prev, schedule_label: event.target.value }))} placeholder="Schedule label" style={styles.input} /><select value={form.category} onChange={(event) => setForm((prev) => ({ ...prev, category: event.target.value }))} style={styles.input}>{categories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><select value={form.status} onChange={(event) => setForm((prev) => ({ ...prev, status: event.target.value }))} style={styles.input}>{statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><input value={form.failure_threshold} onChange={(event) => setForm((prev) => ({ ...prev, failure_threshold: event.target.value }))} type="number" min="1" max="100" placeholder="Failure threshold" style={styles.input} /><input value={form.next_run_at} onChange={(event) => setForm((prev) => ({ ...prev, next_run_at: event.target.value }))} type="datetime-local" style={styles.input} /><select value={form.owner_platform_user_id} onChange={(event) => setForm((prev) => ({ ...prev, owner_platform_user_id: event.target.value }))} style={styles.input}><option value="">No owner</option>{(users.data || []).map((user) => <option key={user.id} value={user.id}>{user.email}</option>)}</select><select value={form.runbook_id} onChange={(event) => setForm((prev) => ({ ...prev, runbook_id: event.target.value }))} style={styles.input}><option value="">No runbook</option>{(runbooks.data?.runbooks || []).map((runbook) => <option key={runbook.id} value={runbook.id}>{runbook.title}</option>)}</select></div><textarea value={form.notes} onChange={(event) => setForm((prev) => ({ ...prev, notes: event.target.value }))} placeholder="Notes" style={styles.textarea} /><div style={styles.actions}><button type="button" onClick={() => save.mutate()} disabled={save.isPending || !form.name || !form.job_key} style={styles.primaryButton}>{editingId ? 'Save job' : 'Create job'}</button>{editingId ? <button type="button" onClick={() => { setEditingId(null); setForm(emptyForm); }} style={styles.secondaryButton}>Cancel edit</button> : null}</div></section> : null}
      {runJobId && canWrite ? <section style={styles.panel}><h2 style={styles.sectionTitle}>Record job run</h2><div style={styles.grid4}><select value={runForm.last_status} onChange={(event) => setRunForm((prev) => ({ ...prev, last_status: event.target.value }))} style={styles.input}>{(response?.run_statuses || ['success','failed','skipped','running']).map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><input value={runForm.last_duration_ms} onChange={(event) => setRunForm((prev) => ({ ...prev, last_duration_ms: event.target.value }))} type="number" min="0" placeholder="Duration ms" style={styles.input} /><input value={runForm.next_run_at} onChange={(event) => setRunForm((prev) => ({ ...prev, next_run_at: event.target.value }))} type="datetime-local" style={styles.input} /><input value={runForm.last_error} onChange={(event) => setRunForm((prev) => ({ ...prev, last_error: event.target.value }))} placeholder="Error / note" style={styles.input} /></div><div style={styles.actions}><button type="button" onClick={() => recordRun.mutate()} disabled={recordRun.isPending} style={styles.primaryButton}>Save run result</button><button type="button" onClick={() => setRunJobId(null)} style={styles.secondaryButton}>Cancel</button></div></section> : null}
      <section style={styles.panel}><h2 style={styles.sectionTitle}>Jobs</h2>{jobs.isLoading ? <p>Loading jobs…</p> : null}{rows.length === 0 && !jobs.isLoading ? <p>No jobs found.</p> : null}<div style={styles.cards}>{rows.map((job) => <article key={job.id} style={styles.card}><div style={styles.cardTop}><div><strong>{job.name}</strong><div style={styles.muted}>{job.job_key}</div></div><span style={statusStyle(job)}>{label(job.status)}</span></div><div style={styles.details}><span>Category: {label(job.category)}</span><span>Schedule: {job.schedule_label || '—'}</span><span>Owner: {job.owner_email || '—'}</span><span>Runbook: {job.runbook_title || '—'}</span><span>Last run: {dateTime(job.last_run_at)}</span><span>Last status: {label(job.last_status)}</span><span>Duration: {job.last_duration_ms ?? '—'} ms</span><span>Next run: {dateTime(job.next_run_at)}</span><span>Failures: {job.consecutive_failures}/{job.failure_threshold}</span></div>{job.last_error ? <p style={styles.errorText}>{job.last_error}</p> : null}{job.notes ? <p style={styles.note}>{job.notes}</p> : null}{canWrite ? <div style={styles.actions}><button type="button" onClick={() => { setEditingId(job.id); setForm(toForm(job)); }} style={styles.secondaryButton}>Edit</button><button type="button" onClick={() => { setRunJobId(job.id); setRunForm(runFormDefault); }} style={styles.secondaryButton}>Record run</button>{job.status !== 'archived' ? <button type="button" onClick={() => archive.mutate(job.id)} style={styles.dangerButton}>Archive</button> : null}</div> : null}</article>)}</div></section>
    </div>
  );
}

const styles: Record<string, CSSProperties> = { page: { display: 'flex', flexDirection: 'column', gap: 20 }, header: { display: 'flex', justifyContent: 'space-between', gap: 16 }, title: { margin: 0, fontSize: 28 }, subtitle: { margin: '6px 0 0', color: '#555', maxWidth: 900 }, metrics: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 12 }, metric: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 14, padding: 16, display: 'flex', flexDirection: 'column', gap: 4 }, panel: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 16, padding: 18, display: 'flex', flexDirection: 'column', gap: 12 }, sectionTitle: { margin: 0, fontSize: 18 }, grid3: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 10 }, grid4: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 10, alignItems: 'center' }, input: { padding: '10px 12px', border: '1px solid #d1d5db', borderRadius: 10 }, textarea: { padding: '10px 12px', border: '1px solid #d1d5db', borderRadius: 10, minHeight: 86 }, checkRow: { display: 'flex', alignItems: 'center', gap: 8, color: '#374151' }, actions: { display: 'flex', gap: 8, flexWrap: 'wrap' }, primaryButton: { background: '#111827', color: '#fff', border: 0, borderRadius: 10, padding: '10px 14px', cursor: 'pointer' }, secondaryButton: { background: '#f3f4f6', color: '#111827', border: '1px solid #d1d5db', borderRadius: 10, padding: '8px 12px', cursor: 'pointer' }, dangerButton: { background: '#fee2e2', color: '#991b1b', border: '1px solid #fecaca', borderRadius: 10, padding: '8px 12px', cursor: 'pointer' }, cards: { display: 'grid', gap: 12 }, card: { border: '1px solid #e5e7eb', borderRadius: 14, padding: 14, display: 'flex', flexDirection: 'column', gap: 10 }, cardTop: { display: 'flex', justifyContent: 'space-between', gap: 12 }, details: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 8, color: '#374151', fontSize: 13 }, badge: { borderRadius: 999, padding: '4px 9px', background: '#eef2ff', color: '#3730a3', alignSelf: 'flex-start' }, badgeGood: { borderRadius: 999, padding: '4px 9px', background: '#dcfce7', color: '#166534', alignSelf: 'flex-start' }, badgeWarn: { borderRadius: 999, padding: '4px 9px', background: '#fef3c7', color: '#92400e', alignSelf: 'flex-start' }, badgeDanger: { borderRadius: 999, padding: '4px 9px', background: '#fee2e2', color: '#991b1b', alignSelf: 'flex-start' }, badgeMuted: { borderRadius: 999, padding: '4px 9px', background: '#f3f4f6', color: '#4b5563', alignSelf: 'flex-start' }, muted: { color: '#6b7280', fontSize: 13 }, errorText: { margin: 0, color: '#991b1b', background: '#fef2f2', padding: 10, borderRadius: 10 }, note: { margin: 0, color: '#374151', background: '#f9fafb', padding: 10, borderRadius: 10 } };


// Recent Runs support added for operational job troubleshooting.


export const operationalJobRunHistoryEnabled = true;

// Recent execution history support enabled.
