import type { CSSProperties } from 'react';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { platformApiRequest } from '../lib/platformApi';

type PlatformUser = { id: string; email: string; name: string; role: string; is_active: boolean; mfa_enabled?: boolean; last_login_at?: string | null; locked_until?: string | null };
const roles = ['superadmin','support','platform_viewer','support_l1','support_l2','security','billing','ops','tenant_success','readonly_audit'];
export default function PlatformUsersPage() {
  const qc = useQueryClient();
  const [form, setForm] = useState({ email: '', name: '', role: 'platform_viewer', password: '' });
  const q = useQuery({ queryKey: ['platform', 'users'], queryFn: () => platformApiRequest<PlatformUser[]>('/platform/users') });
  const create = useMutation({ mutationFn: () => platformApiRequest('/platform/users', { method: 'POST', body: JSON.stringify(form) }), onSuccess: async () => { setForm({ email: '', name: '', role: 'platform_viewer', password: '' }); await qc.invalidateQueries({ queryKey: ['platform','users'] }); } });
  const patch = useMutation({ mutationFn: ({ id, body }: { id: string; body: object }) => platformApiRequest(`/platform/users/${id}`, { method: 'PATCH', body: JSON.stringify(body) }), onSuccess: async () => qc.invalidateQueries({ queryKey: ['platform','users'] }) });
  const revoke = useMutation({ mutationFn: (id: string) => platformApiRequest(`/platform/users/${id}/revoke-sessions`, { method: 'POST' }) });
  return <div style={styles.page}><h1>Platform users</h1><p style={styles.muted}>Manage HLA/platform staff accounts, roles, activation, and sessions.</p><section style={styles.panel}><h2>Create platform user</h2><div style={styles.form}><input style={styles.input} placeholder="Email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/><input style={styles.input} placeholder="Name" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/><select style={styles.input} value={form.role} onChange={(e)=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><input style={styles.input} placeholder="Temporary password" type="password" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/><button style={styles.button} onClick={()=>create.mutate()} disabled={create.isPending}>Create</button></div>{create.error ? <div style={styles.error}>{create.error instanceof Error ? create.error.message : 'Create failed'}</div> : null}</section><section style={styles.panel}><h2>Users</h2>{q.isLoading ? 'Loading…' : <table style={styles.table}><thead><tr><th style={styles.th}>Name</th><th style={styles.th}>Email</th><th style={styles.th}>Role</th><th style={styles.th}>Status</th><th style={styles.th}>Security</th><th style={styles.th}>Actions</th></tr></thead><tbody>{(q.data||[]).map(u=><tr key={u.id}><td style={styles.td}>{u.name}</td><td style={styles.td}>{u.email}</td><td style={styles.td}><select value={u.role} onChange={(e)=>patch.mutate({ id: u.id, body: { role: e.target.value } })}>{roles.map(r=><option key={r}>{r}</option>)}</select></td><td style={styles.td}>{u.is_active ? 'Active' : 'Disabled'}</td><td style={styles.td}>{u.mfa_enabled ? 'MFA on' : 'MFA off'}{u.locked_until ? ` / locked until ${u.locked_until}` : ''}</td><td style={styles.td}><button style={styles.button} onClick={()=>patch.mutate({ id: u.id, body: { is_active: !u.is_active } })}>{u.is_active ? 'Disable' : 'Activate'}</button> <button style={styles.button} onClick={()=>revoke.mutate(u.id)}>Revoke sessions</button></td></tr>)}</tbody></table>}</section></div>;
}
const styles: Record<string, CSSProperties> = { page:{display:'flex',flexDirection:'column',gap:16}, muted:{color:'#6b7280'}, panel:{background:'#fff',borderRadius:16,padding:20,boxShadow:'0 12px 36px rgba(15,23,42,.08)',overflowX:'auto'}, form:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}, input:{padding:10,border:'1px solid #d1d5db',borderRadius:10}, button:{padding:'8px 10px',borderRadius:10,border:'1px solid #d1d5db',cursor:'pointer'}, table:{width:'100%',borderCollapse:'collapse'}, th:{textAlign:'left',padding:10,borderBottom:'1px solid #e5e7eb'}, td:{padding:10,borderBottom:'1px solid #f3f4f6'}, error:{background:'#fee2e2',color:'#991b1b',borderRadius:12,padding:12,marginTop:10} };
