import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: { display: 'flex', flexDirection: 'column', gap: 16, minWidth: 0 },
  hero: { display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'center', padding: 20, border: '1px solid #e2e8f0', borderRadius: 16, background: '#ffffff', boxShadow: '0 1px 2px rgba(15, 23, 42, 0.03), 0 8px 24px rgba(15, 23, 42, 0.035)' },
  eyebrow: { margin: 0, color: '#1d4ed8', fontWeight: 800, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em' },
  title: { margin: '6px 0', fontSize: 22, lineHeight: 1.25, color: '#0f172a' },
  subtitle: { margin: 0, color: '#64748b', maxWidth: 860, fontSize: 14, lineHeight: 1.55 },
  tabs: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  tab: { border: '1px solid #cbd5e1', background: '#ffffff', color: '#334155', borderRadius: 9, padding: '8px 11px', cursor: 'pointer' },
  activeTab: { border: '1px solid #dbeafe', background: '#eff6ff', color: '#1d4ed8', borderRadius: 9, padding: '8px 11px', cursor: 'pointer', fontWeight: 800 },
  disabledTab: { border: '1px solid #e5e7eb', background: '#f8fafc', color: '#94a3b8', borderRadius: 9, padding: '8px 11px', cursor: 'not-allowed' },
  grid: { display: 'grid', gridTemplateColumns: 'minmax(330px, 0.82fr) minmax(0, 1.68fr)', gap: 16, alignItems: 'start', minWidth: 0 },
  stack: { display: 'flex', flexDirection: 'column', gap: 16, minWidth: 0 },
  statGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: 14, marginTop: 14 },
  metricsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 14 },
  formGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12, alignItems: 'end' },
  cardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 14 },
  metricCard: { border: '1px solid #e2e8f0', borderRadius: 12, padding: 15, background: '#ffffff', boxShadow: '0 1px 2px rgba(15, 23, 42, 0.03)' },
  metricLabel: { display: 'block', fontSize: 12, color: '#64748b', marginBottom: 6, fontWeight: 700 },
  metricValue: { display: 'block', fontSize: 25, lineHeight: 1.08, color: '#0f172a', fontWeight: 800 },
  metricHelper: { display: 'block', fontSize: 11.5, color: '#64748b', marginTop: 7, lineHeight: 1.4 },
  card: { minWidth: 0, padding: 18, border: '1px solid #e2e8f0', borderRadius: 14, background: '#ffffff', boxShadow: '0 1px 2px rgba(15, 23, 42, 0.03), 0 8px 24px rgba(15, 23, 42, 0.035)' },
  cardTitle: { margin: '0 0 14px', paddingBottom: 10, borderBottom: '1px solid #f1f5f9', color: '#0f172a', fontSize: 17, fontWeight: 800, lineHeight: 1.3 },
  sectionTitle: { margin: '0 0 14px', fontSize: 20, color: '#0f172a', fontWeight: 800 },
  field: { display: 'flex', flexDirection: 'column', gap: 5, marginBottom: 11 },
  label: { fontSize: 12.5, fontWeight: 700, color: '#334155', lineHeight: 1.35 },
  input: { width: '100%', minHeight: 40, border: '1px solid #cbd5e1', borderRadius: 8, padding: '9px 11px', color: '#0f172a', background: '#ffffff', font: 'inherit' },
  textarea: { width: '100%', border: '1px solid #cbd5e1', borderRadius: 8, padding: '9px 11px', color: '#0f172a', background: '#ffffff', font: 'inherit', resize: 'vertical' },
  inlineGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12 },
  inlineInput: { minWidth: 180, minHeight: 36, border: '1px solid #cbd5e1', borderRadius: 8, padding: '7px 10px', color: '#0f172a', font: 'inherit' },
  checkboxRow: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12, color: '#334155', fontWeight: 700 },
  primaryButton: { minHeight: 38, border: '1px solid transparent', background: '#2563eb', color: '#ffffff', borderRadius: 8, padding: '9px 14px', fontWeight: 700, lineHeight: 1.2, cursor: 'pointer', boxShadow: '0 1px 2px rgba(37, 99, 235, 0.18)' },
  secondaryButton: { minHeight: 38, border: '1px solid #cbd5e1', background: '#ffffff', color: '#0f172a', borderRadius: 8, padding: '9px 14px', fontWeight: 700, lineHeight: 1.2, cursor: 'pointer', marginTop: 8 },
  smallButton: { minHeight: 34, border: '1px solid transparent', background: '#2563eb', color: '#ffffff', borderRadius: 8, padding: '7px 10px', fontWeight: 700, cursor: 'pointer', boxShadow: '0 1px 2px rgba(37, 99, 235, 0.14)' },
  secondarySmallButton: { minHeight: 34, border: '1px solid #cbd5e1', background: '#ffffff', color: '#0f172a', borderRadius: 8, padding: '7px 10px', fontWeight: 700, cursor: 'pointer' },
  dangerButton: { minHeight: 34, border: '1px solid #fecaca', background: '#ffffff', color: '#dc2626', borderRadius: 8, padding: '7px 10px', fontWeight: 700, cursor: 'pointer' },
  disabledButton: { minHeight: 34, border: '1px solid #e2e8f0', background: '#e2e8f0', color: '#94a3b8', borderRadius: 8, padding: '7px 10px', fontWeight: 700, cursor: 'not-allowed', boxShadow: 'none' },
  actions: { display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' },
  success: { padding: '10px 12px', borderRadius: 10, background: '#ecfdf5', color: '#047857', border: '1px solid #a7f3d0', fontSize: 13 },
  error: { padding: '10px 12px', borderRadius: 10, background: '#fef2f2', color: '#b91c1c', border: '1px solid #fecaca', fontSize: 13 },
  helper: { margin: 0, color: '#64748b', fontSize: 13, lineHeight: 1.5 },
  muted: { margin: '0 0 8px', color: '#64748b', fontSize: 11.5, lineHeight: 1.4, wordBreak: 'break-all' },
  pre: { margin: 0, padding: 12, borderRadius: 10, background: '#0f172a', color: '#f8fafc', overflowX: 'auto', fontSize: 12 },
  tableWrap: { overflowX: 'auto', minWidth: 0 },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: { textAlign: 'left', fontSize: 11.5, color: '#475569', borderBottom: '1px solid #e2e8f0', padding: '9px 10px', whiteSpace: 'nowrap', fontWeight: 700 },
  td: { borderBottom: '1px solid #f1f5f9', padding: '10px', verticalAlign: 'top', color: '#0f172a', fontSize: 13, lineHeight: 1.45 }
};
